import time
import logging
import hashlib
import math
from cogniagent.execution import win32_input

logger = logging.getLogger(__name__)

# Basic safety setup (replaces pyautogui configuration)
win32_input.enable_dpi_awareness()

class ActionRouter:
    """Routes VLM tool calls to Windows native system inputs using ctypes.
    
    Clean, simple execution — no retry hacks. The agent loop handles
    self-correction: if a click misses, the next screenshot shows it,
    and the model reasons about what to do differently.
    """
    
    def __init__(self, config):
        self.config = config

    @staticmethod
    def resolve_click_coordinates(action_data: dict, original_dims: tuple, screen_origin: object = (0, 0)) -> tuple[tuple[int, int] | None, str | None]:
        """Translate validated model coordinates into virtual-desktop pixels.

        Coordinates outside the model contract are rejected, never clamped to
        an edge.  Edge-clamping turned a malformed coordinate into a real click
        on an unrelated control, which is exactly the behaviour this execution
        layer must avoid.
        """
        if not isinstance(original_dims, tuple) or len(original_dims) != 2:
            return None, "Invalid source dimensions for action execution."
        orig_w, orig_h = original_dims
        if (
            isinstance(orig_w, bool)
            or isinstance(orig_h, bool)
            or not isinstance(orig_w, int)
            or not isinstance(orig_h, int)
            or orig_w <= 0
            or orig_h <= 0
        ):
            return None, "Source dimensions must be positive integers."
        if not isinstance(action_data, dict):
            return None, "Failed to parse action JSON from VLM."

        x_val = action_data.get("x")
        y_val = action_data.get("y")
        valid_coordinate = lambda value: (
            isinstance(value, (int, float))
            and not isinstance(value, bool)
            and math.isfinite(value)
            and 0 <= value <= 1000
        )
        if not valid_coordinate(x_val) or not valid_coordinate(y_val):
            return None, "Click coordinates must be finite numbers in the range [0, 1000]."

        if (
            not isinstance(screen_origin, tuple)
            or len(screen_origin) != 2
            or any(isinstance(value, bool) or not isinstance(value, int) for value in screen_origin)
        ):
            return None, "Invalid screenshot origin for action execution."

        origin_x, origin_y = screen_origin
        # 1000 is a valid normalized endpoint and maps to the last pixel of the
        # captured monitor, not a coordinate one pixel beyond it.
        local_x = min(orig_w - 1, int((x_val / 1000.0) * orig_w))
        local_y = min(orig_h - 1, int((y_val / 1000.0) * orig_h))
        return (origin_x + local_x, origin_y + local_y), None

    @staticmethod
    def action_signature(vlm_result: dict) -> str | None:
        """Return a privacy-preserving signature used to block failed repeats."""
        action_data = vlm_result.get("parsed_action") if isinstance(vlm_result, dict) else None
        if not isinstance(action_data, dict):
            return None
        tool_name = action_data.get("tool_name")
        if tool_name == "click":
            label = action_data.get("element", "")
            if not isinstance(label, str):
                label = ""
            return f"click:{action_data.get('x')!r}:{action_data.get('y')!r}:{label.strip().casefold()[:160]}"
        if tool_name == "type":
            text = action_data.get("text")
            if not isinstance(text, str):
                return None
            digest = hashlib.sha256(text.encode("utf-8")).hexdigest()[:16]
            return f"type:{len(text)}:{digest}:{bool(action_data.get('submit', False))}"
        if tool_name == "key_press":
            key = action_data.get("key")
            return f"key:{key.strip().casefold()}" if isinstance(key, str) else None
        if tool_name == "scroll":
            direction = action_data.get("direction")
            return f"scroll:{direction}" if isinstance(direction, str) else None
        return None

    def execute_vlm_action(self, vlm_result: dict, original_dims: tuple) -> dict:
        """Execute a tool_call generated by the Holo3 VLM."""
        logger.info(f"Executing VLM Action: {vlm_result.get('action_desp', '')}")
        
        results = []
        is_done = False
        success = True
        
        action_data = vlm_result.get("parsed_action")
        if not action_data or not isinstance(action_data, dict):
            return {
                "success": False,
                "detail": "Failed to parse action JSON from VLM.",
                "is_done": False
            }
            
        action_type = action_data.get("tool_name")
        
        try:
            if action_type == "click":
                coords, coordinate_error = self.resolve_click_coordinates(
                    action_data,
                    original_dims,
                    vlm_result.get("screen_origin", (0, 0)),
                )
                element = action_data.get("element")
                if not isinstance(element, str) or not element.strip() or len(element) > 300:
                    success = False
                    results.append("Click action requires a concise target description.")
                elif coordinate_error:
                    success = False
                    results.append(coordinate_error)
                else:
                    x, y = coords
                    win32_input.mouse_click(x, y)
                    results.append(f"Clicked [{x}, {y}]")
                    time.sleep(self.config.execution.click_pause)
                    
            elif action_type == "type":
                text = action_data.get("text", "")
                submit = action_data.get("submit", False)
                if not isinstance(text, str):
                    return {
                        "success": False,
                        "detail": "Text action requires a string value.",
                        "is_done": False
                    }
                if len(text) > self.config.safety.max_text_input_characters:
                    return {
                        "success": False,
                        "detail": "Text action exceeds the configured safety limit.",
                        "is_done": False
                    }
                if not isinstance(submit, bool):
                    return {
                        "success": False,
                        "detail": "Text submit flag must be a boolean.",
                        "is_done": False
                    }
                interval = self.config.execution.typing_interval
                win32_input.type_text(text, interval=interval)
                results.append(f"Typed {len(text)} character(s)")
                
                if submit:
                    win32_input.key_press("enter")
                    results.append("Pressed Enter")
                time.sleep(self.config.execution.click_pause)
                
            elif action_type == "key_press":
                key = action_data.get("key")
                if isinstance(key, str) and key.strip():
                    normalized_key = "".join(key.lower().split())
                    # Check banned shortcuts
                    if normalized_key in self.config.safety.banned_shortcuts:
                        return {
                            "success": False,
                            "detail": "Banned shortcut blocked",
                            "is_done": False
                        }
                    
                    # Support key combinations like win+r, ctrl+c
                    if "+" in normalized_key:
                        parts = normalized_key.split("+")
                        if not 2 <= len(parts) <= 3 or any(not part for part in parts):
                            return {
                                "success": False,
                                "detail": "Invalid hotkey format.",
                                "is_done": False,
                            }
                        # Validate all keys before pressing any modifier.  This
                        # prevents malformed model output leaving Ctrl/Alt/Win
                        # held down after a partial hotkey execution.
                        for part in parts:
                            win32_input.resolve_vk(part)
                        win32_input.hotkey(*parts)
                        results.append(f"Pressed hotkey '{normalized_key}'")
                    else:
                        win32_input.resolve_vk(key)
                        win32_input.key_press(key)
                        results.append(f"Pressed key '{key}'")
                    time.sleep(self.config.execution.click_pause)
                else:
                    success = False
                    results.append("Missing key for key_press action.")
                    
            elif action_type == "scroll":
                direction = action_data.get("direction", "down")
                if direction not in {"up", "down"}:
                    return {
                        "success": False,
                        "detail": "Scroll direction must be 'up' or 'down'.",
                        "is_done": False
                    }
                amount = 300 if direction == "up" else -300
                win32_input.mouse_scroll(amount)
                results.append(f"Scrolled {direction}")
                time.sleep(self.config.execution.click_pause)
                
            elif action_type == "wait":
                duration = action_data.get("duration", 3)
                if isinstance(duration, bool) or not isinstance(duration, (int, float)):
                    return {
                        "success": False,
                        "detail": "Wait duration must be a number.",
                        "is_done": False
                    }
                duration = max(1, min(float(duration), self.config.safety.max_wait_seconds))
                logger.info(f"Waiting for {duration} seconds...")
                time.sleep(duration)
                results.append(f"Waited for {duration} seconds")
                
            elif action_type == "get_open_apps":
                apps = win32_input.get_open_windows()
                results.append(f"Open applications: {apps}")
                
            elif action_type == "switch_to_app":
                app_title = action_data.get("app_title", "")
                if not isinstance(app_title, str) or not app_title.strip() or len(app_title) > 160:
                    return {
                        "success": False,
                        "detail": "Application title is missing or exceeds the safety limit.",
                        "is_done": False
                    }
                focused = win32_input.focus_window(app_title)
                if focused:
                    results.append(f"Switched focus to application matching '{app_title}'")
                else:
                    success = False
                    results.append(f"Could not find any open application matching '{app_title}'")
                    
            elif action_type == "minimize_all_apps":
                win32_input.minimize_all_windows()
                results.append("Minimized all windows to show desktop")
                
            elif action_type == "terminate":
                status = action_data.get("status", "success")
                reason = action_data.get("reason", "Unknown")
                is_done = True
                success = (status == "success")
                results.append(f"Terminated: {status} ({reason})")
                
            else:
                success = False
                results.append(f"Unknown tool_name: {action_type}")
                
        except RuntimeError:
            # Re-raise RuntimeError so the failsafe / corner-boundary exception
            # always aborts execution immediately (cannot be silenced).
            raise
        except Exception as e:
            logger.error(f"Execution failed on tool '{action_type}': {e}")
            success = False
            results.append(str(e))
            
        return {
            "success": success, 
            "detail": "; ".join(results), 
            "is_done": is_done
        }
